// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	Address    *string   `json:"address"`
	Identifier *string   `json:"identifier"`
	Topics     []*string `json:"topics"`
	Data       *string   `json:"data"`
}

type SubscriptionEntry struct {
	Address    *string   `json:"address"`
	Identifier *string   `json:"identifier"`
	Topics     []*string `json:"topics"`
}
